spring:
  application:
    name: cex-xscale-common-utils-service
  profiles:
    active: ${ENVIRONMENT:local}
  cloud.config.name: "cex-xscale-common-utils-service"
  config:
    import: 'optional:configserver:${CONFIG_SERVER_URL}'
  jackson:
    default-property-inclusion: NON_NULL
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_DB_URL}
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}
    hikari:
      schema: ${POSTGRES_DB_SCHEMA}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      validation-timeout: ${DB_CONNECTION_VALIDATION_TIMEOUT:5000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      maximum-pool-size: ${DB_MAX_POOL_SIZE:25}
      connection-init-sql: SET lock_timeout TO '50s'
  jpa:
    database: POSTGRESQL
    ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: false
        generate_statistics: ${CONN_STATS:false}
